apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.mariadbpvc.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.mariadbpvc.path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
  labels:
    app: mariadb
spec:
  accessModes:
    - {{ .Values.mariadbpv.accessmode }}
  resources:
    requests:
      storage: {{ .Values.mariadbpv.storage }} 

