apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.wordpresspvc.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.wordpresspvc.path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: manual
  accessModes: 
    - {{ .Values.wordpresspv.accessmode }}
  resources:
    requests:
      storage: {{ .Values.wordpresspv.storage }}
