apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - port: {{ .Values.wordpresssvc.port }}
      targetPort: {{ .Values.wordpresssvc.targetport }}
      protocol: TCP #default
      nodePort: 31000
  type: {{ .Values.wordpresssvc.type }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec: # specification for deployment resource
  replicas: {{ .Values.wordpressdeploy.replicas }}
  selector:
    matchLabels:
      app: wordpress
  template: # blueprint for pods
    metadata:
      labels:
        app: wordpress
    spec: # specification for pods
      containers:
      - name: wordpress
        image: {{ .Values.wordpressdeploy.image }} ##4.8-apache
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mariadb-configmap
              key: database_url
          #value: mariadb-internal-service
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-root-password
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DEBUG
          value: "1"
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
